version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vendure
      POSTGRES_DB: vendure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  vendure:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=need-it
      - DB_PASSWORD=zsolika
      - DB_NAME=vendure
      - ADMIN_API_PORT=3000
      - SHOP_API_PORT=3001

volumes:
  pgdata:
