version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: need-it
      POSTGRES_PASSWORD: zsolika
      POSTGRES_DB: vendure
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
