[build]
  builder = "nixpacks"
  buildCommand = "yarn build"
  startCommand = "yarn start"
  installCommand = "yarn install --frozen-lockfile"
  nixpacks = { version = "node20" }

[deploy]
  startCommand = "yarn start"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartDelay = 5

[build.environment]
  NODE_ENV = "production"
  NODE_OPTIONS = "--max_old_space_size=1024"

[deploy.regions]
  primary = "europe-west1"
  fallback = "us-east1"
